project:
  type: website
  output-dir: _site

lang: en-GB
freeze: auto

format:
  html:
    toc: true
    toc-title: Contents
    number-sections: true
    theme: cosmo
  pdf:
    documentclass: article
    number-sections: true

metadata:
  date-format: iso

execute:
  echo: false

website:
  title: "Investigating Science (Stage 6)"
  navbar:
    left:
      - text: Unit
        href: inv-sci-unit.qmd
      - text: Exam Mapping
        href: exam-mapping.qmd
      - text: Quizzes
        menu:
          - text: M5–M8 Mixed Quiz 1
            href: quizzes/quiz-1.qmd
          - text: M5–M8 Mixed Quiz 2
            href: quizzes/quiz-2.qmd
          - text: M5–M8 Mixed Quiz 3
            href: quizzes/quiz-3.qmd
          - text: M5–M8 Mixed Quiz 4
            href: quizzes/quiz-4.qmd
          - text: M5–M8 Mixed Quiz 5
            href: quizzes/quiz-5.qmd
      - text: Study Plan (8 weeks)
        href: study-plan.qmd
      - text: Worksheets
        menu:
          - text: Worksheet 1
            href: worksheets/worksheet-1.qmd
          - text: Worksheet 2
            href: worksheets/worksheet-2.qmd
