project:
  type: website
  output-dir: _site

lang: en-GB
freeze: auto

format:
  html:
    toc: true
    toc-title: Contents
    number-sections: true
    theme: cosmo
  pdf:
    documentclass: article
    number-sections: true

metadata:
  date-format: iso

execute:
  echo: false

website:
  title: "Investigating Science (Stage 6)"
  navbar:
    left:
      - text: Unit
        href: inv-sci-unit.qmd
      - text: Worksheets
        menu:
          - text: Worksheet 1
            href: worksheets/worksheet-1.qmd
          - text: Worksheet 2
            href: worksheets/worksheet-2.qmd
